-- MySQL Script generated by MySQL Workbench
-- Mon Nov 11 11:24:39 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema LittleLemonDB
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `LittleLemonDB` ;

-- -----------------------------------------------------
-- Schema LittleLemonDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `LittleLemonDB` DEFAULT CHARACTER SET utf8 ;
USE `LittleLemonDB` ;

-- -----------------------------------------------------
-- Table `LittleLemonDB`.`customers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LittleLemonDB`.`customers` (
  `customer_id` SMALLINT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `phone_number` INT NOT NULL,
  PRIMARY KEY (`customer_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LittleLemonDB`.`staff`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LittleLemonDB`.`staff` (
  `staff_id` SMALLINT NOT NULL AUTO_INCREMENT,
  `role` VARCHAR(45) NOT NULL,
  `salary` INT NOT NULL,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`staff_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LittleLemonDB`.`bookings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LittleLemonDB`.`bookings` (
  `booking_id` SMALLINT NOT NULL AUTO_INCREMENT,
  `date` DATETIME NOT NULL,
  `table_number` TINYINT NOT NULL DEFAULT 0,
  `customer_id` SMALLINT NOT NULL,
  `staff_id` SMALLINT NOT NULL,
  PRIMARY KEY (`booking_id`),
  INDEX `customer_id_fk_idx` (`customer_id` ASC) VISIBLE,
  INDEX `staff_id_fk_idx` (`staff_id` ASC) VISIBLE,
  CONSTRAINT `bookings_customer_id_fk`
    FOREIGN KEY (`customer_id`)
    REFERENCES `LittleLemonDB`.`customers` (`customer_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `bookings_staff_id_fk`
    FOREIGN KEY (`staff_id`)
    REFERENCES `LittleLemonDB`.`staff` (`staff_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LittleLemonDB`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LittleLemonDB`.`orders` (
  `order_id` SMALLINT NOT NULL AUTO_INCREMENT,
  `order_date` DATETIME NOT NULL,
  `total_cost` DECIMAL(5,2) NOT NULL DEFAULT 0.0,
  `customer_id` SMALLINT NOT NULL,
  `staff_id` SMALLINT NOT NULL,
  PRIMARY KEY (`order_id`),
  INDEX `customer_id_fk_idx` (`customer_id` ASC) VISIBLE,
  INDEX `staff_id_fk_idx` (`staff_id` ASC) VISIBLE,
  CONSTRAINT `orders_customer_id_fk`
    FOREIGN KEY (`customer_id`)
    REFERENCES `LittleLemonDB`.`customers` (`customer_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `orders_staff_id_fk`
    FOREIGN KEY (`staff_id`)
    REFERENCES `LittleLemonDB`.`staff` (`staff_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LittleLemonDB`.`deliveries`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LittleLemonDB`.`deliveries` (
  `delivery_id` SMALLINT NOT NULL AUTO_INCREMENT,
  `delivery_date` DATETIME NOT NULL,
  `status` CHAR(6) NOT NULL DEFAULT 'NOTDEL',
  `order_id` SMALLINT NOT NULL,
  PRIMARY KEY (`delivery_id`),
  INDEX `order_id_fk_idx` (`order_id` ASC) VISIBLE,
  CONSTRAINT `delivery_order_id_fk`
    FOREIGN KEY (`order_id`)
    REFERENCES `LittleLemonDB`.`orders` (`order_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LittleLemonDB`.`menu_options`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LittleLemonDB`.`menu_options` (
  `menu_option_id` SMALLINT NOT NULL AUTO_INCREMENT,
  `cuisine` VARCHAR(45) NOT NULL,
  `starter` VARCHAR(45) NOT NULL,
  `course` VARCHAR(45) NOT NULL,
  `drink` VARCHAR(45) NOT NULL,
  `dessert` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`menu_option_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LittleLemonDB`.`order_menu_options`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LittleLemonDB`.`order_menu_options` (
  `order_menu_options_id` INT NOT NULL AUTO_INCREMENT,
  `order_id` SMALLINT NOT NULL,
  `menu_option_id` SMALLINT NOT NULL,
  `quantity` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`order_menu_options_id`),
  INDEX `order_id_fk_idx` (`order_id` ASC) VISIBLE,
  INDEX `menu_option_id_fk_idx` (`menu_option_id` ASC) VISIBLE,
  CONSTRAINT `orrder_menu_order_id_fk`
    FOREIGN KEY (`order_id`)
    REFERENCES `LittleLemonDB`.`orders` (`order_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `order_menu_menu_option_id_fk`
    FOREIGN KEY (`menu_option_id`)
    REFERENCES `LittleLemonDB`.`menu_options` (`menu_option_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
