-- MySQL Script generated by MySQL Workbench
-- Mon Nov 11 23:14:33 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema LittleLemonDM
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `LittleLemonDM` ;

-- -----------------------------------------------------
-- Schema LittleLemonDM
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `LittleLemonDM` DEFAULT CHARACTER SET utf8 ;
USE `LittleLemonDM` ;

-- -----------------------------------------------------
-- Table `LittleLemonDM`.`customers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LittleLemonDM`.`customers` (
  `customer_id` SMALLINT NOT NULL AUTO_INCREMENT,
  `full_name` VARCHAR(50) NOT NULL,
  `contact_number` CHAR(12) NOT NULL,
  `email` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`customer_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LittleLemonDM`.`menu_items`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LittleLemonDM`.`menu_items` (
  `menu_item_id` SMALLINT NOT NULL AUTO_INCREMENT,
  `course_name` VARCHAR(45) NOT NULL,
  `starter_name` VARCHAR(45) NOT NULL,
  `desert_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`menu_item_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LittleLemonDM`.`menus`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LittleLemonDM`.`menus` (
  `menu_id` SMALLINT NOT NULL AUTO_INCREMENT,
  `menu_item_id` SMALLINT NOT NULL,
  `menu_name` VARCHAR(45) NOT NULL,
  `cuisine` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`menu_id`),
  INDEX `menus_menu_item_id_idx` (`menu_item_id` ASC) VISIBLE,
  CONSTRAINT `menus_menu_item_id`
    FOREIGN KEY (`menu_item_id`)
    REFERENCES `LittleLemonDM`.`menu_items` (`menu_item_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LittleLemonDM`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LittleLemonDM`.`orders` (
  `order_id` SMALLINT NOT NULL AUTO_INCREMENT,
  `menu_id` SMALLINT NOT NULL,
  `customer_id` SMALLINT NOT NULL,
  `total_cost` DECIMAL(5,2) NOT NULL DEFAULT 0.0,
  `quantity` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`order_id`),
  INDEX `orders_customer_id_idx` (`customer_id` ASC) VISIBLE,
  INDEX `orders_menu_id_idx` (`menu_id` ASC) VISIBLE,
  CONSTRAINT `orders_customer_id`
    FOREIGN KEY (`customer_id`)
    REFERENCES `LittleLemonDM`.`customers` (`customer_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `orders_menu_id`
    FOREIGN KEY (`menu_id`)
    REFERENCES `LittleLemonDM`.`menus` (`menu_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LittleLemonDM`.`bookings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LittleLemonDM`.`bookings` (
  `booking_id` SMALLINT NOT NULL AUTO_INCREMENT,
  `customer_id` SMALLINT NOT NULL,
  `booking_date` DATETIME NOT NULL,
  `table_number` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`booking_id`),
  INDEX `bookings_customer_id_idx` (`customer_id` ASC) VISIBLE,
  CONSTRAINT `bookings_customer_id`
    FOREIGN KEY (`customer_id`)
    REFERENCES `LittleLemonDM`.`customers` (`customer_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
